# Configuration for stitching HadCRUT from SST and LSAT files using
# Weight files


sst_path: "/noc/mpoc/surface/josidd/git/kriging_fork/scratch/HadCRUT/output/distance/tos/kriged_member_{member:03d}.nc"
sst_var_name: "sst_anom_perturbed"

lsat_path: "/noc/mpoc/surface/josidd/git/kriging_fork/scratch/HadCRUT/output/distance/tas/kriged_member_{member:03d}.nc"
lsat_var_name: "lsat_anom_perturbed"

weights_path: "/noc/mpoc/surface_data/HadCRUT5_extra/HadCRUT.5.0.2.0.analysis.weights.nc"
weights_var_name: "weights"
weight_indicator: "lsat"

out_path: "/noc/mpoc/surface/josidd/git/kriging_fork/scratch/HadCRUT/output/distance/stitched/kriged_member_{member:03d}.nc"
out_var_name: "combined_perturbed"
