domain:
  west: !!float -180.0
  east: !!float 180.0
  south: !!float -90.0
  north: !!float 90.0

  startyear: !!int 1900
  endyear: !!int 2023

  variable: "mat"

climatology:
  path: "/noc/mpoc/surface_data/CLASS/NMAT_glosat/data/HARMONICS/iter_3/1961_1990/climatology_1961_1990_iter3_t10m.nc"
  # path: "/noc/mpoc/surface_data/ESA_CCI1deg_daily/ANOMALY"
  # path: "/noc/mpoc/surface_data/agfaul/kriging_split_into_modules/ESA_CCI_SST_climatology_pentads/ESA_CCI_SST_climatology_pentads_ESA.nc"
  # path: "/noc/mpoc/surface_data/agfaul/kriging_split_into_modules/ESA_CCI_SST_climatology_pentads/ESA_CCI_SST_climatology_pentads_MetOffice.nc"
  # path: "/noc/mpoc/surface_data/agfaul/kriging_split_into_modules/esa_cci_climatology_monthly.nc"
  # daily SST clim comes as directory with multiple files, not one nc file
  # path: "/noc/mpoc/surface_data/ESA_CCIv2.1clim/"
  metoffice_climatology: "/noc/mpoc/surface_data/agfaul/kriging_split_into_modules/ESA_CCI_SST_climatology_pentads/ESA_CCI_SST_climatology_pentads_MetOffice.nc"

observations:
  data : "/noc/mpoc/surface/ICOADS_R3_PY_PROC/GROUPS/*/{year}_{month:02d}.feather"
  # "/noc/mpoc/surface_data/ICOADS_NETCDF_R3_ALL/ICOADS_R3.0.0_"
  # ""/noc/mpoc/surface_data/ICOADS_NETCDF_R3_ALL/*.nc""

  # qc: "/noc/mpoc/surface/MAT_production/data/QC/{year}_{month:02d}.feather"
  icoads_qc_flags : "/noc/mpoc/surface/ICOADS_R3_PY_PROC/GROUPS_DUP_ELIM/*/{year}_{month:02d}.feather"
  # icoads_qc_flags_tracked : "/noc/mpoc/surface/ICOADS_R3_PY_PROC/GROUPS_GRAPH_TRACKED/*/{year}_{month:02d}.feather"

covariance:
  # path: "/noc/mpoc/surface_data/stchan/data2/kriging_tests/Global_With_Poles_UKMO_Grid/locally_build_covariances/eigen_test/via_eigenvec_removal_v2"
  # "/noc/mpoc/surface_data/stchan/data2/kriging_tests/AtlIndPac/updated"
  # covariances_180_60
  # "/noc/mpoc/surface_data/stchan/data2/kriging_tests/AtlIndPac/updated"
  # "/noc/mpoc/surface_data/stchan/data2/kriging_tests/test_data_2p5_mask_sst_cov_4_aga_1p0_T0p25"
  #
  # path: "/noc/mpoc/surface_data/stchan/data2/kriging_tests/test_data_2p5_mask_sst_cov_4_aga_1p0_T0p25/covariance_01_v_eq_0p5_Atlantic_Ocean_1p0_T0p25.nc"
  path: "/noc/mpoc/surface_data/agfaul/DIFFERENT_EMPIRICAL_COVARIANCES/world/global_covariance_{month:02d}.nc"
  # path: "/noc/mpoc/surface_data/agfaul/DIFFERENT_EMPIRICAL_COVARIANCES/atlantic/month_covariance/atlantic_january_covariance.nc"
  ellipse_path: "/noc/mpoc/surface_data/stchan/data2/kriging_tests/Global_With_Poles_UKMO_Grid/underlying_ellipses/Global_With_Poles_{month:02d}_1.0_85.5.nc"

mask:
  # path: "/noc/mpoc/surface_data/stchan/data2/kriging_tests/test_data_2p5_mask_sst_cov_4_aga_1p0_T0p25/1985/data_sample_01_Atlantic_Ocean_1p0_T0p25.nc"
  # global (-180, 180, -60, 60) derived from ellipses
  # path: "/noc/mpoc/surface_data/stchan/data2/kriging_tests/AtlIndPac/landmask_Atlantic_Pacific_Indian_1p0_T0p25_physical_distances_0p5centered.nc"
  # /noc/mpoc/surface_data/stchan/data2/kriging_tests/AtlIndPac/landmask_Atlantic_Pacific_Indian_1p0_T0p25_physical_distances.nc
  # global (180, 180, -90, 90) derived from ESA data
  path: "/noc/mpoc/surface_data/agfaul/KRIGING_SPLIT_INTO_MODULES_LOCAL/world_landmask.nc"
  # path: "/noc/mpoc/surface_data/agfaul/DIFFERENT_EMPIRICAL_COVARIANCES/world/world_landmask.nc"

  # options for temporary ice are: masked, set to -1.8, (TODO: specific to reconstructed scene)
  # ice_masking: true

parameters:
  sig_ms: !!float 0.73
  sig_mb: !!float 0.24
  sig_bs: !!float 1.47
  sig_bb: !!float 0.38

  height_adjustments: "/noc/mpoc/surface/MAT_production/data/height_adjustments"
  adjusted_height: !!int 10


output:
  path: "/noc/mpoc/surface/agfaul/SST_KRIGED_ELLIPSES_GLOBAL/"
  # time_resolution: "year"
  time_resolution: "month"
