# config file for main_HadCRUT.py

domain:
  west: !!float -180.
  east: !!float 180.
  south: !!float -90.
  north: !!float 90.

  startyear: !!int 1850
  endyear: !!int 2023

sst:
  observations: "/noc/mpoc/surface_data/HadSST4_extra/HadSST.4.0.1.0_median.nc"
  distance_interpolation_covariance: "/noc/mpoc/surface_data/ESA_CCI5deg_month_extra/ANOMALY/SpatialScales/locally_build_covariances/sea_sigma_covariance_euclidean.npy"
  ellipse_interpolation_covariance: "/noc/mpoc/surface_data/ESA_CCI5deg_month_extra/ANOMALY/SpatialScales/locally_build_covariances"
  error_covariance: "/noc/mpoc/surface_data/HadCRUT5_extra/error_cov"
  uncorrelated_uncertainty: "/noc/mpoc/surface_data/HadCRUT5_extra/HadCRUT.5.0.2.0.uncorrelated.nc"

  range: !!float 1300.
  sigma: !!float 0.6
  matern: !!float 1.5


lsat:
  observations: "/noc/mpoc/surface_data/CRUTEM.5.0.2.0/CRUTEM.5.0.2.0.anomalies.nc"
  distance_interpolation_covariance: "/noc/mpoc/surface_data/ESA_CCI5deg_month_extra/ANOMALY/SpatialScales/locally_build_covariances/lnd_sigma_covariance_euclidean.npy"
  ellipse_interpolation_covariance: "/noc/mpoc/surface/ERA5_SURFTEMP_500deg_monthly/ANOMALY/SpatialScales/locally_build_covariances"
  error_covariance: "/noc/mpoc/surface_data/HadCRUT5_extra/HadCRUT.5.0.2.0.uncorrelated_dummy"

  range: !!float 1300.
  sigma: !!float 1.2
  matern: !!float 1.5

output:
  path: "/noc/mpoc/surface/agfaul/HadCRUT/output/ellipse"
